name: Package Theme Updates

on:
  push:
    paths-ignore:
      - 'PackedThemes/**'
      - '.*'
      - '*.md'
      - 'LICENSE'

jobs:
  package-themes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          
      - name: Package Modified Themes
        run: |
          # Get modified files from the last commit (excluding PackedThemes and root files)
          MODIFIED_FILES=$(git show --name-only --pretty="" HEAD | grep -v '^PackedThemes/' | grep -v '^[^/]*$' || true)
          
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No theme files were modified"
            exit 0
          fi
          
          echo "Modified files:"
          echo "$MODIFIED_FILES"
          
          # Extract unique folder names from modified files (without adding quotes)
          FOLDERS=$(echo "$MODIFIED_FILES" | cut -d'/' -f1 | sort -u)
          
          echo "Folders to process:"
          echo "$FOLDERS"
          
          # Store the absolute path to the workspace
          WORKSPACE="$PWD"
          
          # Create PackedThemes directory if it doesn't exist
          mkdir -p PackedThemes
          
          # Process each modified theme folder using null delimiter to handle spaces
          echo "$FOLDERS" | tr '\n' '\0' | while IFS= read -r -d '' folder; do
            if [ -d "$folder" ]; then
              echo "Packaging $folder..."
              # Create temporary directory structure
              mkdir -p "temp/mnt/SDCARD/Themes"
              cp -r "$folder" "temp/mnt/SDCARD/Themes/"
              
              # Create 7z archive from workspace root
              7z a -r "${WORKSPACE}/PackedThemes/${folder}.7z" "${WORKSPACE}/temp/mnt"
              
              # Cleanup
              rm -rf temp
            fi
          done
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add PackedThemes/*.7z
          git commit -m "Update theme packages" || echo "No changes to commit"
          git push
