name: Package Theme Updates

on:
  push:
    paths-ignore:
      - 'PackedThemes/**'
      - '.*'
      - '*.md'
      - 'LICENSE'

jobs:
  package-themes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          
      - name: Package Modified Themes
        run: |
          # Get modified files from the last commit (excluding PackedThemes and root files)
          MODIFIED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD | grep -v '^PackedThemes/' | grep -v '^[^/]*$' || true)
          
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No theme files were modified"
            exit 0
          fi
          
          echo "Modified files:"
          echo "$MODIFIED_FILES"
          
          # Extract unique folder names from modified files and handle spaces in names
          FOLDERS=$(echo "$MODIFIED_FILES" | cut -d'/' -f1 | sort -u | sed 's/^/"/;s/$/"/')
          
          echo "Folders to process:"
          echo "$FOLDERS"
          
          # Create PackedThemes directory if it doesn't exist
          mkdir -p PackedThemes
          
          # Process each modified theme folder
          echo "$FOLDERS" | while read -r folder; do
            # Remove quotes from folder name for checks
            folder_clean=$(echo "$folder" | sed 's/^"//;s/"$//')
            
            if [ -d "$folder_clean" ]; then
              echo "Packaging $folder_clean..."
              # Create temporary directory structure
              mkdir -p "temp/mnt/SDCARD/Themes"
              cp -r "$folder_clean" "temp/mnt/SDCARD/Themes/"
              
              # Change to temp directory and create 7z archive
              cd temp
              7z a -r "../PackedThemes/${folder_clean}.7z" "mnt"
              cd ..
              
              # Cleanup
              rm -rf temp
            fi
          done
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add PackedThemes/*.7z
          git commit -m "Update theme packages" || echo "No changes to commit"
          git push
