name: Update Theme Gallery

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Theme Gallery
        id: generate-gallery
        run: |
          # Create temporary files
          TEMP_FILE=$(mktemp)
          GALLERY_CONTENT=$(mktemp)
          
          # Generate the new gallery content
          echo -e "## Theme Gallery\n" > "$GALLERY_CONTENT"
          echo -e "| Preview | Theme | Download |\n|---------|--------|----------|\n" >> "$GALLERY_CONTENT"
          
          # Process each theme folder
          for theme_dir in */; do
            if [ -d "$theme_dir" ] && [ "$theme_dir" != "PackedThemes/" ]; then
              theme_name="${theme_dir%/}"
              preview_path="$theme_dir/preview.png"
              packed_path="PackedThemes/$theme_name.7z"
              
              if [ -f "$preview_path" ] && [ -f "$packed_path" ]; then
                # Create properly encoded URLs
                preview_url="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/${theme_dir}preview.png"
                download_url="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/PackedThemes/${theme_name}.7z"
                
                preview_url=$(echo "$preview_url" | sed -e 's/ /%20/g')
                download_url=$(echo "$download_url" | sed -e 's/ /%20/g')
                
                echo "| <img src=\"$preview_url\" width=\"200\"> | $theme_name | [Download]($download_url) |" >> "$GALLERY_CONTENT"
              fi
            fi
          done
          
          # Extract content before Theme Gallery
          awk '/^## Theme Gallery/{exit} {print}' README.md > "$TEMP_FILE"
          
          # Add the new gallery content
          cat "$GALLERY_CONTENT" >> "$TEMP_FILE"
          
          # Add footer content
          echo -e "\nThemes here are in .7z format, you can place them into your Themes folder and spruce will automatically unzip them." >> "$TEMP_FILE"
          
          # Replace the original README
          mv "$TEMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update theme gallery" || exit 0
          git push
