name: Update Theme Gallery

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Theme Gallery
        id: generate-gallery
        run: |
          # Create temporary file for new content
          TEMP_FILE=$(mktemp)
          
          # Copy header content until the preview section
          sed '/^![spruce-home-page]/q' README.md > "$TEMP_FILE"
          
          # Add gallery header
          echo -e "\n## Theme Gallery\n" >> "$TEMP_FILE"
          
          # Initialize table header
          echo -e "| Preview | Theme | Download |\n|---------|--------|----------|\n" >> "$TEMP_FILE"
          
          # Process each theme folder
          for theme_dir in */; do
            if [ -d "$theme_dir" ] && [ "$theme_dir" != "PackedThemes/" ]; then
              theme_name="${theme_dir%/}"
              preview_path="$theme_dir/preview.png"
              packed_path="PackedThemes/$theme_name.7z"
              
              if [ -f "$preview_path" ] && [ -f "$packed_path" ]; then
                # Get raw GitHub URL for the files
                preview_url="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/$preview_path"
                download_url="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/$packed_path"
                
                # Add row to table
                echo "| <img src=\"$preview_url\" width=\"200\"> | $theme_name | [Download]($download_url) |" >> "$TEMP_FILE"
              fi
            fi
          done
          
          # Add the remaining content from the original README
          sed -n '/^Themes here/,$p' README.md >> "$TEMP_FILE"
          
          # Replace original README with new content
          mv "$TEMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update theme gallery" || exit 0
          git push
